name: Action Test

on:
  pull_request:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    name: Scraper running
    steps:
      - uses: actions/checkout@v2.1.0
      - name: 'get changed files'
        uses: jitterbit/get-changed-files@v1
        id: generate-changed-files
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Printing
        run: |
          echo "All:"
          echo "${{ steps.generate-changed-files.outputs.all }}"
          echo "Added:"
          echo "${{ steps.generate-changed-files.outputs.added }}"
          echo "Removed:"
          echo "${{ steps.generate-changed-files.outputs.removed }}"
          echo "Renamed:"
          echo "${{ steps.generate-changed-files.outputs.renamed }}"
          echo "Modified:"
          echo "${{ steps.generate-changed-files.outputs.modified }}"
          echo "Added+Modified:"
          echo "${{ steps.generate-changed-files.outputs.added_modified }}"
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: lighthouse-summary
          message: ${{ steps.generate-changed-files.outputs.all }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}